service: trunk-based-artifact-promotion

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 30
  memorySize: 256
  logRetentionInDays: 30
  tags:
    service: ${self:service}
    Environment: ${self:provider.stage}
    CreatedBy: serverless
    Repository: https://github.com/clowdhaus/trunk-based-artifact-promotion
    Version: ${opt:version, 'dev'}
    CommitSha: ${opt:commitSha, 'dev'}
  stackTags: ${self:provider.tags}

package:
  patterns:
    - '!**/**'
    - '*.py'

functions:
  hello:
    handler: handler.hello
